import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'



const index = () => {
  return (
    <>
      <Head>
        <title>Snehasish Dey | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar/> */}
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      
    </>
  )
}

export default index